In [64]:
import numpy as np
import matplotlib.pyplot as plt
import numpy.linalg as linalg

In [65]:
np.set_printoptions(precision=4, suppress=True)
np.random.seed(1)

time = np.linspace(0, 10 * np.pi, 1000)

series = np.random.normal(0, 1, 1000) * np.sin(np.linspace(0, 10 * np.pi, 1000))
noise = np.random.rand(1000) * 2 - 1
noise_var = np.var(noise)
print(noise_var)

0.3286865541420873


In [66]:
length = series.shape[0]
g_p = []
for lag in range(series.shape[0]):
    correlation = np.mean(series[lag:] * noise[:noise.shape[0]-lag])  # расчет корреляции x и eps
    g_p.append(correlation / noise_var)
    if lag == 0:
        print(g_p)

g_p = np.array(g_p)

print(g_p.shape)

[np.float64(0.053438324275501145)]
(1000,)


In [69]:
p, q = 2, 4
lag = p + q
g = np.concatenate((np.zeros(lag), g_p))
print(g[lag])
SLAU_b = np.empty((q, p + 1))
b = np.empty((q, 1))

SLAU_a = np.empty((p, p))
a = np.empty((p, 1))
for i in range(q + 1, q + 1 + p):
    SLAU_a[i - q - 1] = -g[lag + i - 1 - np.arange(p)]
    a[i - q - 1] = g[lag + i]

print(SLAU_a)
print(a)
A = linalg.solve(SLAU_a, a).reshape(p)
A = np.concatenate((np.ones(1), A))
print(A)
B = np.zeros(q)

for i in range(1, q + 1):
    B[i - 1] = np.sum(g[lag + i - np.arange(p + 1)] * A)
B = np.concatenate((np.ones(1), B))
print(B)
print(g[lag: lag + q + p + 1])

0.053438324275501145
[[-0.0724  0.0207]
 [-0.0523 -0.0724]]
[[ 0.0523]
 [-0.054 ]]
[ 1.     -0.4225  1.0516]
[ 1.     -0.0263  0.0648 -0.0275  0.0885]
[ 0.0534 -0.0037  0.007  -0.0207  0.0724  0.0523 -0.054 ]


In [70]:
noise = np.random.rand(1000) * 2 - 1
noise_var = np.var(noise)
print(noise_var)

0.33228582417572944
